### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cherryhomes** [creame/connect-polylang-elementor#1]
Hello, 

today i got the failure. can someone help me to fix this please?

WordPress-Version 5.9
Aktives Theme: Hello Elementor (Version 2.4.2)
Aktuelles Plugin: Polylang Connect for Elementor (Version 2.0.0)
PHP-Version 7.4.26-he.0

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 88 der Datei /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-content/plugins/connect-polylang-elementor/connect-polylang-elementor.php verursacht. Fehlermeldung: Uncaught Error: Class 'ConnectPolylangElementor\ConnectPlugins' not found in /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-content/plugins/connect-polylang-elementor/connect-polylang-elementor.php:88
Stack trace:
#0 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-includes/class-wp-hook.php(307): ConnectPolylangElementor\setup('')
#1 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(Object(WPMailSMTP\Connect), Array)
#2 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#3 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-settings.php(450): do_action('plugins_loaded')
#4 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-config.php(96): require_once('/is/htdocs/wp10...')
#5 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-load.php(50): require_once('/is/htdocs/wp10...')
#6 /is/htdocs/wp1077089_YDKQ2XBBT6/www/EnzianNEU/wp-admin/admin.php(34): require_once('/is/htdocs/wp10...')
#7 /is/htdocs/wp1077089_YDKQ2X

**Comment by pacotole** [comment]
There was a problem with capital letters in the path. It's already fixed in version 2.0.1
