### ISSUE TITLE
Built-in Wordpress Widget "Elementor Library" not automatically translated

### ISSUE THREAD

**Issue by lennertdaniels** [creame/connect-polylang-elementor#14]
Wordpress, by default, allows you to add widgets to so-called "[sidebars](https://developer.wordpress.org/themes/functionality/sidebars/)", accessed through `/wp-admin/widgets.php`.

When you install Elementor, a Wordpress-widget "Elementor Library" becomes available, which allows you to add any Elementor template to one of those sidebars. This instance of the template does not get automatically translated, unlike the Elementor built-in "Template Widget". You have to manually set the language, as shown in my screenshot.

Inserting an Elementor template in a sidebar using a shortcode does work as expected and gets automatically translated.

![image](https://github.com/creame/connect-polylang-elementor/assets/23380289/c5d464fc-a4ce-4202-bcb9-da79b37581ff)

Could this be implemented?

**Comment by pacotole** [comment]
Thanks for the report. I didn't know this feature.
Automatic translation will be included in the next version.
