### ISSUE TITLE
Uncaught TypeError in includes/connect-plugins.php:155 using Elementor Pro 3.18.1

### ISSUE THREAD

**Issue by ChristianSchaffner** [creame/connect-polylang-elementor#16]
Dear Connect Polylang for Elementor team,

Since updating to the latest Elementor Pro (Version 3.18.1) on our WordPress webpage we get the following crash from Connect Polylang for Elementor Version 2.4.3  (using Polylang Pro Version 3.5.3), which leads to the Elementor Pro side panel not loading properly. Below is the crash report (resulting in the Elementor Pro editing panel not loading. 

I "hacked" connect-plugins.php by commenting line 155. This solved the problem, but I am not sure if I created other problems. 

Thanks and kind regards,
Christian.
 

`[Sat Dec 16 13:18:24.844042 2023] [php:error] [pid 457320] [client 172.226.132.52:38705] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /instances/home/energyweekprd/htdocs/wp-content/plugins/connect-polylang-elementor/includes/connect-plugins.php:155
Stack trace:
#0 /instances/home/energyweekprd/htdocs/wp-content/plugins/connect-polylang-elementor/includes/connect-plugins.php(155): in_array()
#1 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-hook.php(324): ConnectPolylangElementor\\ConnectPlugins->query_all_languages()
#2 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#3 /instances/home/energyweekprd/htdocs/wp-includes/plugin.php(565): WP_Hook->do_action()
#4 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-query.php(1140): do_action_ref_array()
#5 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-query.php(1868): WP_Query->parse_query()
#6 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-query.php(3824): WP_Query->get_posts()
#7 /instances/home/energyweekprd/htdocs/wp-includes/post.php(2452): WP_Query->query()
#8 /instances/home/energyweekprd/htdocs/wp-content/plugins/neuron-core-bifrost/functions.php(393): get_posts()
#9 /instances/home/energyweekprd/htdocs/wp-content/plugins/neuron-core-bifrost/includes/widgets/template/base.php(44): neuron_get_elementor_templates()
#10 /instances/home/energyweekprd/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(2356): NeuronElementor\\Widgets\
euronTemplate->_register_controls()
#11 /instances/home/energyweekprd/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(1044): Elementor\\Controls_Stack->init_controls()
#12 /instances/home/energyweekprd/htdocs/wp-content/plugins/elementor/includes/base/controls-stack.php(541): Elementor\\Widget_Base->init_controls()
#13 /instances/home/energyweekprd/htdocs/wp-content/plugins/elementor/includes/base/widget-base.php(181): Elementor\\Controls_Stack->get_stack()
#14 /instances/home/energyweekprd/htdocs/wp-content/plugins/elementor/includes/managers/widgets.php(388): Elementor\\Widget_Base->get_stack()
#15 [internal function]: Elementor\\Widgets_Manager->ajax_get_widget_types_controls_config()
#16 /instances/home/energyweekprd/htdocs/wp-content/plugins/elementor/core/common/modules/ajax/module.php(176): call_user_func()
#17 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-hook.php(324): Elementor\\Core\\Common\\Modules\\Ajax\\Module->handle_ajax_request()
#18 /instances/home/energyweekprd/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#19 /instances/home/energyweekprd/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#20 /instances/home/energyweekprd/htdocs/wp-admin/admin-ajax.php(188): do_action()
#21 {main}
  thrown in /instances/home/energyweekprd/htdocs/wp-content/plugins/connect-polylang-elementor/includes/connect-plugins.php on line 155, referer: https://energyweek.ethz.ch/wp-admin/post.php?post=36869&action=elementor
`

**Comment by pacotole** [comment]
Thanks for the report. The fix will be included in the next version.
