### ISSUE TITLE
Dropdown max height not heigh enough for many languages

### ISSUE THREAD

**Issue by pless84** [creame/connect-polylang-elementor#7]
We have 16 active languages and will activate more in the future.
As it is now not all languages are shown in the dropdown and the top one is half hidden.
I think I have found the issue is with the max-height of 300px, can this be dynamic? or at least higher?
<img width="960" alt="Skærmbillede 2022-09-16 144634" src="https://user-images.githubusercontent.com/324145/190642119-9c57b593-fd50-44cd-8ccc-1805b22f48e1.png">
<img width="960" alt="Skærmbillede 2022-09-16 144458" src="https://user-images.githubusercontent.com/324145/190642191-4e90d603-8478-4e93-b170-871ed31d6e63.png">

**Comment by pacotole** [comment]
Wow, I didn't think that would be the case.
I have an idea to make it dynamic with a CSS variable but I need time to test it.
I will keep this in mind to do so as soon as I can.

**Comment by pacotole** [comment]
Problem solved, try with v2.3.2 😉
